version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basic3tier
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Basic3Tier: "Host=postgres;Port=5432;Database=basic3tier;Username=postgres;Password=admin123"
    ports:
      - "80:80"
      - "443:443"
