name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on a PR to 'main' branch

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
 
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
 
      - name: Restore and build the solution
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release
 
      - name: Run tests
        run: |
          dotnet test --no-build --configuration Release

      - name: Set up DockerHub credentials
        uses: docker/login-action@v2.2.0
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List directory structure for debugging
        run: |
         echo "Listing current directory"
         ls -alh
         echo "Listing contents of root"
         ls -alh /
         echo "Listing contents of api directory"
         ls -alh ./api
      - name: Run a simple test in the /api directory
        run: |
          cd ./api
          echo "Running tests or checking for issues"
          docker build -t test-image .

      - name: Build and test Backend API
        run: |
          cd ./api 
          docker build -t mirmika/backend:latest .
          docker run --rm mirmika/backend:latest

      - name: Build and test Frontend UI
        run: |
         cd ./ui  
         docker build -t mirmika/frontend:latest . 
         docker run --rm mirmika/frontend:latest 

      - name: Scan code with SonarQube
        uses: sonarsource/sonarcloud-github-action@master
        with:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Secure SonarQube token stored in GitHub Secrets
         SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}  # SonarQube server URL stored as a GitHub variable

      - name: Tag Docker Images with commit SHA
        run: |
         docker tag mirmika/backend:latest mirmika/backend:${{ github.sha }}
         docker tag mirmika/frontend:latest mirmika/frontend:${{ github.sha }}

      - name: Push Docker Images to DockerHub
        run: |
         docker push mirmika/backend:latest
         docker push mirmika/frontend:latest
         docker push mirmika/backend:${{ github.sha }}
         docker push mirmika/frontend:${{ github.sha }}
