name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on a PR to 'main' branch

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore and build the project
        run: |
          # Specify the path to the .csproj file for your project
          dotnet restore ./api/Basic3Tier.Core/Basic3Tier.Core.csproj  
          dotnet build ./api/Basic3Tier.Core/Basic3Tier.Core.csproj --no-restore --configuration Release

      - name: Run tests
        run: |
          # Specify the .csproj file for running tests
          dotnet test ./api/Tests/Basic3Tier.Core.Tests/Basic3Tier.Core.Tests.csproj --no-build --configuration Release

      - name: Set up DockerHub credentials
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List directory structure for debugging
        run: |
          echo "Listing current directory"
          ls -alh
          echo "Listing contents of api directory"
          ls -alh ./api

      - name: Build and test Backend API
        run: |
          cd ./api/Basic3TierAPI  # Path to the backend API folder
          docker build -t mirmika/backend:latest .
          docker run --rm mirmika/backend:latest

      - name: Build and test Frontend UI
        run: |
          cd ./ui  # Path to the frontend UI folder
          docker build -t mirmika/frontend:latest .
          docker run --rm mirmika/frontend:latest

      - name: Scan code with SonarQube
        uses: sonarsource/sonarcloud-github-action@master
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Tag Docker Images with commit SHA
        run: |
          docker tag mirmika/backend:latest mirmika/backend:${{ github.sha }}
          docker tag mirmika/frontend:latest mirmika/frontend:${{ github.sha }}

      - name: Push Docker Images to DockerHub
        run: |
          docker push mirmika/backend:latest
          docker push mirmika/frontend:latest
          docker push mirmika/backend:${{ github.sha }}
          docker push mirmika/frontend:${{ github.sha }}
