name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
jobs:
 build-test-and-docker:
  runs-on: ubuntu-latest
  services:
    postgres:
      image: postgres:15-alpine
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: basic3tier
      ports:
        - 5432:5432
      options: >-
        --health-cmd="pg_isready -U postgres" 
        --health-interval=10s 
        --health-timeout=5s 
        --health-retries=5

  env:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: basic3tier
    DB_USER: postgres
    DB_PASSWORD: admin123

  steps:
    - name: Check Memory Usage
      run: free -m

    - name: List all running containers
      run: docker ps -a

    - name: Get Container Name
      id: get_container_name  # Ensure this is your step's id
      run: |
          container_name=$(docker ps -a --format "{{.Names}}")
          echo "Container name is: $container_name"
          echo "::set-output name=container_name::$container_name"

    - name: Check if PostgreSQL is running
      run: |
       container_name=${{ steps.get_container_name.outputs.container_name }}
       echo "Checking if PostgreSQL is running in container: $container_name"
      
       # Run the command without -it flags since GitHub Actions does not have TTY support
       if [ -z "$container_name" ]; then
        echo "Error: No container found"
        exit 1
       fi

       # Checking PostgreSQL process inside the container
       docker exec $container_name sh -c "ps aux | grep postgres"

    - name: Check PostgreSQL Configuration Path
      run: |
       container_name=${{ steps.get_container_name.outputs.container_name }}
       echo "Checking PostgreSQL configuration path in container: $container_name"
      
       # List the directory structure to find the correct configuration file
       docker exec $container_name sh -c "ls -l /var/lib/postgresql/data"
       # List the directory structure to find the correct configuration file

    - name: Modify PostgreSQL listen_addresses
      run: |
        container_name=${{ steps.get_container_name.outputs.container_name }}
        echo "Modifying listen_addresses to '*'"
        
        docker exec $container_name sh -c "sed -i 's/^#listen_addresses =.*/listen_addresses = '*'/' /var/lib/postgresql/data/postgresql.conf"
        docker exec $container_name sh -c "sed -i 's/127.0.0.1/0.0.0.0/g' /var/lib/postgresql/data/pg_hba.conf"

    # Step 3: Restart PostgreSQL inside the container to apply changes
    - name: Restart PostgreSQL
      run: |
       container_name=${{ steps.get_container_name.outputs.container_name }}
       echo "Restarting PostgreSQL inside the container"
    
       # Run pg_ctl as the postgres user
       docker exec $container_name su - postgres -c "pg_ctl restart"

    - name: View PostgreSQL Logs
      run: |
        container_name=${{ steps.get_container_name.outputs.container_name }}
        docker logs $container_name

    - name: Test PostgreSQL Connection
      run: |
        container_name=${{ steps.get_container_name.outputs.container_name }}
        echo "Waiting for PostgreSQL connection..."
        until PGPASSWORD=admin123 psql -h $container_name -U postgres -d basic3tier -c "SELECT 1;" 2>/dev/null; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done
        echo "PostgreSQL is ready!"

    # Step to check out the repository
    - name: Check out repository
      uses: actions/checkout@v4


      # Upload .NET test results as artifacts
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
          name: dotnet-results
          path: TestResults

    # Set up DockerHub credentials
    - name: Set up DockerHub credentials
      uses: docker/login-action@v2.2.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and test Backend API
    - name: Build and test Backend API
      run: |
          cd ./api
          docker build -t mirmika/backend:latest .
          docker run --rm mirmika/backend:latest

    # Build and test Frontend UI
    - name: Build and test Frontend UI
      run: |
          cd ./ui 
          docker build -t mirmika/frontend:latest . 
          docker run --rm mirmika/frontend:latest

    # Tag Docker images with commit SHA
    - name: Tag Docker Images with commit SHA
      run: |
          docker tag mirmika/backend:latest mirmika/backend:${{ github.sha }}
          docker tag mirmika/frontend:latest mirmika/frontend:${{ github.sha }}

    # Push Docker Images to DockerHub
    - name: Push Docker Images to DockerHub
      run: |
          docker push mirmika/backend:latest
          docker push mirmika/frontend:latest
          docker push mirmika/backend:${{ github.sha }}
          docker push mirmika/frontend:${{ github.sha }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarQube scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarScanner
      run: |
          dotnet tool install --global dotnet-sonarscanner

    - name: Build and analyze
      shell: bash
      run: |
          # Run SonarQube scan
          dotnet-sonarscanner begin /k:"3-tier-application" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"

          # Specify your project or solution path in the build command
          dotnet build ./api/Basic3Tier.Core/Basic3Tier.Core.csproj --configuration Release

          # End SonarQube scan
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"        
